name: Build and Push Gateway Docker Image

on:
  push:
    branches: [main]
    paths:
      - 'gateway/**'  # รัน workflow เฉพาะถ้าไฟล์ใน gateway เปลี่ยน

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gateway

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./gateway
          file: ./gateway/Dockerfile
          push: true
          tags: wachrwisw12/gateway:latest
